./CCBS ../Examples/test_case/case1/map.xml  ../Examples/test_case/case1/task.xml  ../Examples/test_case/config0.xml > ./case1.txt
./CCBS ../Examples/test_case/case1/map.xml  ../Examples/test_case/case1/task.xml  ../Examples/test_case/config1.xml >> ./case1.txt
./CCBS ../Examples/test_case/case2/map.xml  ../Examples/test_case/case2/task.xml  ../Examples/test_case/config0.xml > ./case2.txt
./CCBS ../Examples/test_case/case2/map.xml  ../Examples/test_case/case2/task.xml  ../Examples/test_case/config1.xml >> ./case2.txt
./CCBS ../Examples/test_case/case3a/map.xml ../Examples/test_case/case3a/task.xml ../Examples/test_case/config0.xml > ./case3a.txt
./CCBS ../Examples/test_case/case3a/map.xml ../Examples/test_case/case3a/task.xml ../Examples/test_case/config1.xml >> ./case3a.txt
./CCBS ../Examples/test_case/case3b/map.xml ../Examples/test_case/case3b/task.xml ../Examples/test_case/config0.xml > ./case3b.txt
./CCBS ../Examples/test_case/case3b/map.xml ../Examples/test_case/case3b/task.xml ../Examples/test_case/config1.xml >> ./case3b.txt
./CCBS ../Examples/test_case/case4a/map.xml ../Examples/test_case/case4a/task.xml ../Examples/test_case/config0.xml > ./case4a.txt
./CCBS ../Examples/test_case/case4a/map.xml ../Examples/test_case/case4a/task.xml ../Examples/test_case/config1.xml >> ./case4a.txt
./CCBS ../Examples/test_case/case4b/map.xml ../Examples/test_case/case4b/task.xml ../Examples/test_case/config0.xml > ./case4b.txt
./CCBS ../Examples/test_case/case4b/map.xml ../Examples/test_case/case4b/task.xml ../Examples/test_case/config1.xml >> ./case4b.txt
./CCBS ../Examples/test_case/case5/map.xml  ../Examples/test_case/case5/task.xml  ../Examples/test_case/config0.xml > ./case5.txt
./CCBS ../Examples/test_case/case5/map.xml  ../Examples/test_case/case5/task.xml  ../Examples/test_case/config1.xml >> ./case5.txt
./CCBS ../Examples/test_case/case6/map.xml  ../Examples/test_case/case6/task.xml  ../Examples/test_case/config0.xml > ./case6.txt
./CCBS ../Examples/test_case/case6/map.xml  ../Examples/test_case/case6/task.xml  ../Examples/test_case/config1.xml >> ./case6.txt
./CCBS ../Examples/test_case/case7/map.xml  ../Examples/test_case/case7/task.xml  ../Examples/test_case/config0.xml > ./case7.txt
./CCBS ../Examples/test_case/case7/map.xml  ../Examples/test_case/case7/task.xml  ../Examples/test_case/config1.xml >> ./case7.txt
./CCBS ../Examples/test_case/case8/map.xml  ../Examples/test_case/case8/task.xml  ../Examples/test_case/config0.xml > ./case8.txt
./CCBS ../Examples/test_case/case8/map.xml  ../Examples/test_case/case8/task.xml  ../Examples/test_case/config1.xml >> ./case8.txt
